.\" Process this file with
.\" groff -t -mandoc -Tascii flaw.7 | less
.\"
.TH flaw 7 "FEBRUARY 2009"
.SH NAME
flaw \- a Lua OO management framework for awesome WM widgets
.SH DESCRIPTION
.B flaw
stands for Fully Loaded AWesome.  It is a LUA object oriented library
providing a thin abstraction layer above awesome widgets.  It is aimed
at being simple and resources efficient.
.sp
To achieve these goals,
.B flaw
provides the following concepts.
.IP gadgets
To add functionality to awesome widgets,
.B flaw
defines gadget objects, which are a wrapper around a widget.  All
gadgets have properties, events, a refresh mechanism and a data
provider (see below).  Gadgets can wrap all awesome widget type,
namely text boxes, image boxes or graphs.
.B flaw
provides many gadgets for common system information (like CPU or
memory activity).
.IP provider
.B flaw
tries to minimise system access and data refresh.  Since all
information do not have the same expiration rate, all gadgets refresh
independently.  And since some gadgets can share information, all data
is provided by providers which can be shared among gadgets.  Providers
maintain status data from the system and refreshes only when necessary
(ie. when the gadget with the shortest refresh rate demands it).
.IP events
Events are a way for the user to modify the gadget behaviour or
properties when some conditions are met.  An event is composed of a
trigger, which computes the condition, and an action.  Event triggers
are tested by the providers only when data changes.  Both the
condition and the action are provided by the user.
.SH USAGE
Before anything else, insert require('flaw') in your configuration file.
.SS The flaw API
.IP flaw.gadget.new
.SH WIDGET TYPES
.SS Battery
.SS CPU
.SS Memory
.SS Network

.SH EXAMPLES

.SH DIAGNOSTICS
.B flaw
should output in .xsession-errors any useful warning, but this is not
the case yet.
.SH BUGS
Certainly a lot.
.br
.B flaw
currently trashes the whole configuration loading if something was
wrong and does not provide diagnostics.
.SH AUTHOR
David Soulayrol <david.soulayrol at gmail dot net>
.SH "SEE ALSO"
.BR awesome (1),
.BR awesome-client (1),
.BR awesomerc (5)
